server:
  port: 8987

turbine:
  aggregator:
    clusterConfig: USER-SERVICE
  app-config: payment-service,user-service
spring:
  application:
    name: turbine-server
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:2000/eureka