server:
  port: 8001

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:2000/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

spring:
  boot:
    admin:
      url: http://localhost:8080
management:
  security:
    enabled: false